version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=note

  note-app:
    image: hamza3991/note:0.0.1
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/note
    depends_on:
      - mongodb
